### PR TITLE
Add st-snazzy to related

### PR DESCRIPTION
**Pull request by Dko1905**
Not much more to say.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What is `st`? Your readme fails to mention that.

**Comment by Dko1905** [comment]
`st` is a terminal, just like urxvt and Alacritty.
Which readme are you talking about, if it's the one in the pull request, it gives just as much info as the other terminals in the list?

**Comment by sindresorhus** [comment]
"Your" readme is the readme of *your* repo. You could at least link to the ST project page.

**Comment by Dko1905** [comment]
I don't find it necessary to explain what application uses the theme, since it's already in the name.
I also don't find it necessary to link to the st project page, since everyone using this theme would already know the terminal. No one ever finds the theme before the terminal.

**Comment by sindresorhus** [comment]
🤷‍♂️

**Comment by Dko1905** [comment]
Well, someone is having a bad day.

**Comment by Dko1905** [comment]
You are also being hypocritical, your own repo [iterm2-snazzy](https://github.com/sindresorhus/iterm2-snazzy) "fails to mention" what iterm2 is, and does not "at least link" to the [iterm2 homepage](https://iterm2.com/).

I just ask for you to fairly reevaluate my pull request.

**Pull request closed without merging**
